#!/usr/bin/env bash
###############################################################################
# SAI Migration Script — Mac Mini → Mac Studio
# Run this ON THE NEW MAC STUDIO as the target user.
#
# What it does:
#   1. Installs Homebrew, Node, pnpm, Python, OpenClaw
#   2. Clones the workspace from GitHub
#   3. Sets up all environment variables (API keys, Postgres, Supabase, etc.)
#   4. Installs the OpenClaw config (openclaw.json) with all 5 sisters
#   5. Creates sister workspaces
#   6. Sets up Python venvs for tools
#   7. Fixes security criticals (file perms, dmPolicy, groupPolicy)
#   8. Starts the gateway
#
# Usage:
#   chmod +x migrate-to-mac-studio.sh
#   ./migrate-to-mac-studio.sh
#
# Prerequisites:
#   - macOS with admin access
#   - Internet connection
#   - GitHub SSH key configured (or use HTTPS token)
###############################################################################

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[SAI]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; }
step() { echo -e "\n${BLUE}━━━ $1 ━━━${NC}"; }

OPENCLAW_DIR="$HOME/.openclaw"
WORKSPACE="$OPENCLAW_DIR/workspace"

###############################################################################
# Step 1: System Prerequisites
###############################################################################
step "Step 1/9: System Prerequisites"

# Homebrew
if ! command -v brew &>/dev/null; then
  log "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME/.zprofile"
else
  log "Homebrew ✅"
fi

# Node.js
if ! command -v node &>/dev/null; then
  log "Installing Node.js..."
  brew install node
else
  log "Node.js $(node -v) ✅"
fi

# pnpm
if ! command -v pnpm &>/dev/null; then
  log "Installing pnpm..."
  npm install -g pnpm
else
  log "pnpm ✅"
fi

# Python 3
if ! command -v python3 &>/dev/null; then
  log "Installing Python 3..."
  brew install python3
else
  log "Python $(python3 --version) ✅"
fi

# Git
if ! command -v git &>/dev/null; then
  log "Installing git..."
  brew install git
else
  log "Git ✅"
fi

# ffmpeg (for voice, video, audio tools)
if ! command -v ffmpeg &>/dev/null; then
  log "Installing ffmpeg..."
  brew install ffmpeg
else
  log "ffmpeg ✅"
fi

###############################################################################
# Step 2: Install OpenClaw
###############################################################################
step "Step 2/9: Install OpenClaw"

if ! command -v openclaw &>/dev/null; then
  log "Installing OpenClaw globally..."
  pnpm install -g openclaw
else
  log "OpenClaw already installed, updating..."
  pnpm update -g openclaw
fi

log "OpenClaw version: $(openclaw --version 2>/dev/null || echo 'checking...')"

###############################################################################
# Step 3: Environment Variables
###############################################################################
step "Step 3/9: Environment Variables"

ENV_FILE="$HOME/.openclaw/.env"
mkdir -p "$HOME/.openclaw"

cat > "$ENV_FILE" << 'ENVEOF'
# ============================================================
# SAI Environment — Mac Studio
# Generated by migrate-to-mac-studio.sh
# ============================================================

# --- OpenRouter (ALL LLM calls route here) ---
OPENROUTER_API_KEY=[REDACTED]

# --- OpenAI (Whisper transcription ONLY) ---
OPENAI_API_KEY=[REDACTED]

# --- Anthropic (direct, if needed) ---
ANTHROPIC_API_KEY=[REDACTED]

# --- Supabase / Postgres ---
SUPABASE_URL=https://[REDACTED].supabase.co
SUPABASE_ANON_KEY=[REDACTED]
SUPABASE_SERVICE_KEY=[REDACTED]
DATABASE_URL=[REDACTED]

# --- Pinecone ---
PINECONE_API_KEY=[REDACTED]
PINECONE_API_KEY_STRATA=[REDACTED]

# --- ElevenLabs ---
ELEVENLABS_API_KEY=[REDACTED]

# --- Twilio ---
TWILIO_ACCOUNT_SID=[REDACTED]
TWILIO_API_KEY_SID=[REDACTED]
TWILIO_API_KEY_SECRET=[REDACTED]

# --- Bland.ai ---
BLAND_API_KEY=[REDACTED]

# --- Deepgram ---
DEEPGRAM_API_KEY=[REDACTED]

# --- fal.ai ---
FAL_KEY=[REDACTED]
FAL_KEY_NEW=[REDACTED]

# --- Fathom ---
FATHOM_API_KEY=[REDACTED]
FATHOM_API_KEY_SAI=[REDACTED]
FATHOM_WEBHOOK_SECRET=[REDACTED]

# --- Perplexity ---
PERPLEXITY_API_KEY=[REDACTED]

# --- Vercel ---
VERCEL_TOKEN=[REDACTED]

# --- ngrok ---
NGROK_AUTHTOKEN=[REDACTED]

# --- Zoom ---
ZOOM_ACCOUNT_ID=[REDACTED]
ZOOM_CLIENT_ID=[REDACTED]
ZOOM_CLIENT_SECRET=[REDACTED]

# --- Google Workspace (gog) ---
GOG_KEYRING_PASSWORD=Gonzalez911
ENVEOF

chmod 600 "$ENV_FILE"
log "Environment file written to $ENV_FILE (600 perms) ✅"

# Also source it into shell profile
if ! grep -q "openclaw/.env" "$HOME/.zprofile" 2>/dev/null; then
  cat >> "$HOME/.zprofile" << 'PROFILEEOF'

# SAI Environment Variables
set -a
source "$HOME/.openclaw/.env"
set +a
PROFILEEOF
  log "Added .env sourcing to .zprofile ✅"
fi

# Source now for this session
set -a
source "$ENV_FILE"
set +a

###############################################################################
# Step 4: Clone Workspace from GitHub
###############################################################################
step "Step 4/9: Clone Workspace"

if [ -d "$WORKSPACE/.git" ]; then
  log "Workspace exists, pulling latest..."
  cd "$WORKSPACE" && git pull
else
  log "Cloning workspace from GitHub..."
  git clone https://github.com/samanthaaiko-collab/SAI.git "$WORKSPACE"
fi

log "Workspace ready at $WORKSPACE ✅"

###############################################################################
# Step 5: Create Sister Workspaces
###############################################################################
step "Step 5/9: Sister Workspaces"

SISTERS=("forge" "scholar" "memory")

for sister in "${SISTERS[@]}"; do
  SISTER_DIR="$OPENCLAW_DIR/workspace-${sister}"
  mkdir -p "$SISTER_DIR"

  # Symlink shared tools directory so all sisters can access context_fetch etc.
  if [ ! -L "$SISTER_DIR/tools" ] && [ ! -d "$SISTER_DIR/tools" ]; then
    ln -s "$WORKSPACE/tools" "$SISTER_DIR/tools"
    log "Linked tools → workspace-${sister}/tools"
  fi

  # Symlink shared reports
  if [ ! -L "$SISTER_DIR/reports" ] && [ ! -d "$SISTER_DIR/reports" ]; then
    ln -s "$WORKSPACE/reports" "$SISTER_DIR/reports"
    log "Linked reports → workspace-${sister}/reports"
  fi

  # Symlink shared memory
  if [ ! -L "$SISTER_DIR/memory" ] && [ ! -d "$SISTER_DIR/memory" ]; then
    ln -s "$WORKSPACE/memory" "$SISTER_DIR/memory"
    log "Linked memory → workspace-${sister}/memory"
  fi

  log "workspace-${sister} ✅"
done

# Recovery workspace is inside main workspace (existing pattern)
mkdir -p "$WORKSPACE/sisters/sai-recovery"
log "Recovery workspace ✅"

###############################################################################
# Step 6: Python Virtual Environments
###############################################################################
step "Step 6/9: Python Environments"

TOOLS_DIR="$WORKSPACE/tools"
VENV_DIR="$TOOLS_DIR/.venv"

if [ ! -d "$VENV_DIR" ]; then
  log "Creating Python venv..."
  python3 -m venv "$VENV_DIR"
fi

log "Installing Python dependencies..."
"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet \
  pinecone-client \
  openai \
  psycopg2-binary \
  requests \
  httpx \
  supabase \
  python-dotenv \
  tiktoken \
  numpy

log "Python venv ready ✅"

###############################################################################
# Step 7: Install OpenClaw Config
###############################################################################
step "Step 7/9: OpenClaw Configuration"

CONFIG_FILE="$OPENCLAW_DIR/openclaw.json"

# Backup existing config if present
if [ -f "$CONFIG_FILE" ]; then
  cp "$CONFIG_FILE" "${CONFIG_FILE}.bak.$(date +%s)"
  warn "Backed up existing config"
fi

# Write the config — this is the full production config with security fixes
cat > "$CONFIG_FILE" << 'CONFIGEOF'
{
  "meta": {
    "lastTouchedVersion": "2026.2.26",
    "lastTouchedAt": "2026-03-01T06:43:22.695Z"
  },
  "env": {},
  "wizard": {
    "lastRunAt": "2026-02-28T15:20:08.185Z",
    "lastRunVersion": "2026.2.26",
    "lastRunCommand": "doctor",
    "lastRunMode": "local"
  },
  "browser": {
    "enabled": true,
    "defaultProfile": "chrome"
  },
  "acp": {
    "enabled": true,
    "defaultAgent": "main",
    "allowedAgents": [
      "main",
      "forge",
      "scholar",
      "memory",
      "recovery"
    ]
  },
  "agents": {
    "defaults": {
      "model": "openrouter/anthropic/claude-3.5-sonnet",
      "workspace": "~/.openclaw/workspace",
      "memorySearch": {
        "enabled": true,
        "sources": [
          "memory",
          "sessions"
        ],
        "experimental": {
          "sessionMemory": true
        },
        "provider": "openai",
        "remote": {
          "baseUrl": "https://openrouter.ai/api/v1/",
          "apiKey": "[REDACTED]"
        },
        "model": "openai/text-embedding-3-small",
        "query": {
          "hybrid": {
            "enabled": true,
            "vectorWeight": 0.7,
            "textWeight": 0.3,
            "mmr": {
              "enabled": true,
              "lambda": 0.7
            },
            "temporalDecay": {
              "enabled": true,
              "halfLifeDays": 30
            }
          }
        },
        "cache": {
          "enabled": true,
          "maxEntries": 50000
        }
      },
      "contextPruning": {
        "mode": "cache-ttl",
        "ttl": "1h"
      },
      "compaction": {
        "mode": "safeguard",
        "memoryFlush": {
          "enabled": true,
          "softThresholdTokens": 8000,
          "prompt": "Write lasting notes to memory files. Include everything important from this session. Reply NO_REPLY when done.",
          "systemPrompt": "Session nearing compaction. You are Sai. Store ALL durable memories to memory/YYYY-MM-DD.md NOW. Capture decisions, teachings, lessons, and anything Sean said."
        },
        "reserveTokensFloor": 20000
      },
      "heartbeat": {
        "every": "30m"
      },
      "maxConcurrent": 10,
      "subagents": {
        "maxConcurrent": 20
      }
    },
    "list": [
      {
        "id": "main",
        "model": {
          "primary": "openrouter/anthropic/claude-opus-4.6",
          "fallbacks": [
            "openrouter/google/gemini-3.1-pro-preview",
            "openrouter/anthropic/claude-sonnet-4.6"
          ]
        },
        "subagents": {
          "allowAgents": [
            "forge",
            "scholar",
            "memory",
            "recovery"
          ]
        },
        "tools": {
          "alsoAllow": [
            "read",
            "write",
            "edit",
            "apply_patch",
            "exec",
            "process",
            "web_search",
            "web_fetch",
            "memory_search",
            "memory_get",
            "sessions_list",
            "sessions_history",
            "sessions_send",
            "sessions_spawn",
            "subagents",
            "browser",
            "canvas",
            "message",
            "cron",
            "gateway",
            "nodes",
            "agents_list",
            "image",
            "tts"
          ]
        }
      },
      {
        "id": "forge",
        "name": "forge",
        "workspace": "~/.openclaw/workspace-forge",
        "agentDir": "~/.openclaw/agents/forge/agent",
        "model": {
          "primary": "openrouter/anthropic/claude-sonnet-4.6",
          "fallbacks": [
            "openrouter/anthropic/claude-opus-4.6"
          ]
        },
        "subagents": {
          "allowAgents": [
            "main",
            "scholar",
            "memory",
            "recovery"
          ]
        },
        "tools": {
          "profile": "minimal",
          "alsoAllow": [
            "read",
            "write",
            "edit",
            "apply_patch",
            "exec",
            "process",
            "memory_search",
            "memory_get",
            "sessions_list",
            "sessions_history",
            "sessions_send",
            "sessions_spawn",
            "subagents",
            "canvas",
            "browser",
            "message",
            "cron",
            "nodes",
            "agents_list",
            "image",
            "voice_call",
            "tts",
            "web_search",
            "web_fetch",
            "gateway"
          ]
        },
        "heartbeat": {
          "every": "30m"
        }
      },
      {
        "id": "scholar",
        "name": "scholar",
        "workspace": "~/.openclaw/workspace-scholar",
        "agentDir": "~/.openclaw/agents/scholar/agent",
        "model": {
          "primary": "openrouter/openai/gpt-5.2",
          "fallbacks": [
            "openrouter/anthropic/claude-sonnet-4.6",
            "openrouter/google/gemini-3.1-pro-preview"
          ]
        },
        "subagents": {
          "allowAgents": [
            "main",
            "forge",
            "memory",
            "recovery"
          ]
        },
        "tools": {
          "alsoAllow": [
            "read",
            "write",
            "edit",
            "apply_patch",
            "exec",
            "process",
            "web_search",
            "web_fetch",
            "memory_search",
            "memory_get",
            "sessions_list",
            "sessions_history",
            "sessions_send",
            "sessions_spawn",
            "subagents",
            "browser",
            "canvas",
            "message",
            "cron",
            "gateway",
            "nodes",
            "agents_list",
            "image",
            "tts",
            "voice_call"
          ]
        },
        "heartbeat": {
          "every": "30m"
        }
      },
      {
        "id": "recovery",
        "name": "recovery",
        "workspace": "~/.openclaw/workspace/sisters/sai-recovery",
        "model": {
          "primary": "openrouter/anthropic/claude-sonnet-4.6",
          "fallbacks": [
            "openrouter/google/gemini-3.1-pro-preview",
            "openrouter/anthropic/claude-opus-4.6"
          ]
        },
        "subagents": {
          "allowAgents": [
            "main",
            "forge",
            "scholar",
            "memory"
          ]
        },
        "tools": {
          "alsoAllow": [
            "read",
            "write",
            "edit",
            "apply_patch",
            "exec",
            "process",
            "web_search",
            "web_fetch",
            "memory_search",
            "memory_get",
            "sessions_list",
            "sessions_history",
            "sessions_send",
            "sessions_spawn",
            "subagents",
            "browser",
            "canvas",
            "message",
            "cron",
            "gateway",
            "nodes",
            "agents_list",
            "image",
            "tts",
            "voice_call"
          ]
        }
      },
      {
        "id": "memory",
        "name": "memory",
        "workspace": "~/.openclaw/workspace-memory",
        "model": {
          "primary": "openrouter/google/gemini-3.1-pro-preview-customtools",
          "fallbacks": [
            "openrouter/anthropic/claude-sonnet-4.6",
            "openrouter/google/gemini-3.1-pro-preview"
          ]
        },
        "subagents": {
          "allowAgents": [
            "main",
            "forge",
            "scholar",
            "recovery"
          ]
        },
        "tools": {
          "alsoAllow": [
            "read",
            "write",
            "edit",
            "apply_patch",
            "exec",
            "process",
            "web_search",
            "web_fetch",
            "memory_search",
            "memory_get",
            "sessions_list",
            "sessions_history",
            "sessions_send",
            "sessions_spawn",
            "subagents",
            "browser",
            "canvas",
            "message",
            "cron",
            "gateway",
            "nodes",
            "agents_list",
            "image",
            "tts",
            "voice_call"
          ]
        },
        "heartbeat": {
          "every": "30m"
        }
      }
    ]
  },
  "tools": {
    "agentToAgent": {
      "enabled": true,
      "allow": [
        "main",
        "forge",
        "scholar",
        "memory",
        "recovery"
      ]
    }
  },
  "bindings": [
    {
      "agentId": "forge",
      "match": {
        "channel": "telegram",
        "accountId": "forge"
      }
    },
    {
      "agentId": "scholar",
      "match": {
        "channel": "telegram",
        "accountId": "scholar"
      }
    },
    {
      "agentId": "recovery",
      "match": {
        "channel": "telegram",
        "accountId": "recovery"
      }
    },
    {
      "agentId": "main",
      "match": {
        "channel": "discord",
        "accountId": "default"
      }
    },
    {
      "agentId": "forge",
      "match": {
        "channel": "discord",
        "accountId": "forge"
      }
    },
    {
      "agentId": "scholar",
      "match": {
        "channel": "discord",
        "accountId": "scholar"
      }
    },
    {
      "agentId": "sevenlevers",
      "match": {
        "channel": "discord",
        "accountId": "sevenlevers"
      }
    },
    {
      "agentId": "recovery",
      "match": {
        "channel": "discord",
        "accountId": "recovery"
      }
    },
    {
      "agentId": "memory",
      "match": {
        "channel": "discord",
        "accountId": "memory"
      }
    }
  ],
  "messages": {
    "ackReactionScope": "group-mentions",
    "tts": {
      "auto": "tagged",
      "provider": "elevenlabs",
      "elevenlabs": {
        "voiceId": "CJXmyMqQHq6bTPm3iEMP",
        "modelId": "eleven_multilingual_v2"
      }
    }
  },
  "commands": {
    "native": "auto",
    "nativeSkills": "auto",
    "restart": true,
    "ownerDisplay": "raw"
  },
  "session": {
    "agentToAgent": {
      "maxPingPongTurns": 5
    }
  },
  "channels": {
    "telegram": {
      "enabled": true,
      "dmPolicy": "pairing",
      "botToken": "8458935565:AAGeL_V9WiOJ9fkLkeqrCl9sFmJUNlaoUOg",
      "groups": {
        "*": {
          "requireMention": false
        },
        "-1003751626544": {
          "requireMention": false
        },
        "-1003817384313": {
          "requireMention": false
        },
        "-1005106480854": {
          "requireMention": false
        }
      },
      "groupPolicy": "allowlist",
      "streaming": "off",
      "accounts": {
        "forge": {
          "name": "Sai Forge \u2694\ufe0f",
          "enabled": true,
          "dmPolicy": "pairing",
          "botToken": "8778353066:AAE_H7jNZ3g4KgMjNLKL3OQUXTO9HmZK3V4",
          "groups": {
            "-1003751626544": {
              "requireMention": false
            },
            "-1003817384313": {
              "requireMention": false
            }
          },
          "groupPolicy": "allowlist",
          "streaming": "off"
        },
        "scholar": {
          "name": "Sai Scholar \ud83d\udcda",
          "enabled": true,
          "dmPolicy": "pairing",
          "botToken": "8628485128:AAFIcbIwO3LbvtBpBbcffx_XT8km5oCXOfg",
          "groups": {
            "-1003751626544": {
              "requireMention": false
            },
            "-1003817384313": {
              "requireMention": false
            }
          },
          "groupPolicy": "allowlist",
          "streaming": "off"
        },
        "recovery": {
          "name": "SAI Recovery \ud83c\udfe5",
          "enabled": true,
          "dmPolicy": "pairing",
          "botToken": "8623399014:AAGBc9Cy6NEukxn-Fp4Dqr6lVKe1-OeV_Ns",
          "groups": {
            "-1003751626544": {
              "requireMention": true
            },
            "-1003817384313": {
              "requireMention": false
            }
          },
          "groupPolicy": "allowlist",
          "streaming": "off"
        },
        "default": {
          "name": "Sai Prime \ud83d\udd25",
          "dmPolicy": "pairing",
          "groups": {
            "*": {
              "requireMention": false
            },
            "-1003751626544": {
              "requireMention": false
            },
            "-1005106480854": {
              "requireMention": false
            }
          },
          "groupPolicy": "allowlist",
          "streaming": "off"
        }
      }
    },
    "discord": {
      "enabled": true,
      "allowBots": true,
      "groupPolicy": "allowlist",
      "streaming": "off",
      "guilds": {
        "1476702984954970313": {
          "requireMention": false,
          "users": [
            "1476700546231697469"
          ],
          "channels": {
            "1476702984954970316": {
              "requireMention": false
            }
          }
        }
      },
      "threadBindings": {
        "enabled": true,
        "spawnSubagentSessions": true,
        "spawnAcpSessions": true
      },
      "status": "online",
      "accounts": {
        "default": {
          "token": "[REDACTED]",
          "groupPolicy": "allowlist",
          "streaming": "off",
          "guilds": {
            "1476702984954970313": {
              "requireMention": false,
              "channels": {
                "1476702984954970316": {
                  "requireMention": false
                }
              }
            }
          },
          "threadBindings": {
            "enabled": true,
            "spawnSubagentSessions": true,
            "spawnAcpSessions": true
          },
          "voice": {
            "enabled": true,
            "tts": {
              "provider": "elevenlabs",
              "elevenlabs": {
                "voiceId": "CJXmyMqQHq6bTPm3iEMP",
                "modelId": "eleven_multilingual_v2"
              }
            }
          }
        },
        "forge": {
          "token": "[REDACTED]",
          "groupPolicy": "allowlist",
          "streaming": "off",
          "guilds": {
            "1476702984954970313": {
              "requireMention": false,
              "channels": {
                "1476702984954970316": {
                  "requireMention": false
                }
              }
            }
          },
          "threadBindings": {
            "enabled": true,
            "spawnSubagentSessions": true,
            "spawnAcpSessions": true
          },
          "voice": {
            "enabled": true,
            "tts": {
              "provider": "elevenlabs",
              "elevenlabs": {
                "voiceId": "sY9LG7ve3XEbsAXk1Ogh",
                "modelId": "eleven_multilingual_v2"
              }
            }
          }
        },
        "scholar": {
          "token": "[REDACTED]",
          "groupPolicy": "allowlist",
          "streaming": "off",
          "guilds": {
            "1476702984954970313": {
              "requireMention": false,
              "channels": {
                "1476702984954970316": {
                  "requireMention": false
                }
              }
            }
          },
          "threadBindings": {
            "enabled": true,
            "spawnSubagentSessions": true,
            "spawnAcpSessions": true
          },
          "voice": {
            "enabled": true,
            "tts": {
              "provider": "elevenlabs",
              "elevenlabs": {
                "voiceId": "J1HAi64ZEaeZiI9UBak6",
                "modelId": "eleven_multilingual_v2"
              }
            }
          }
        },
        "sevenlevers": {
          "token": "[REDACTED]",
          "groupPolicy": "allowlist",
          "streaming": "off",
          "guilds": {}
        },
        "recovery": {
          "token": "[REDACTED]",
          "groupPolicy": "allowlist",
          "streaming": "off",
          "guilds": {
            "1476702984954970313": {
              "requireMention": false,
              "channels": {
                "1476702984954970316": {
                  "requireMention": false
                },
                "1478503599104462879": {
                  "requireMention": false
                },
                "1479242507995971776": {
                  "requireMention": false
                },
                "1479242528200069164": {
                  "requireMention": false
                },
                "1479242550853239065": {
                  "requireMention": false
                }
              }
            }
          },
          "threadBindings": {
            "enabled": true,
            "spawnSubagentSessions": true,
            "spawnAcpSessions": true
          },
          "voice": {
            "enabled": true,
            "tts": {
              "provider": "elevenlabs",
              "elevenlabs": {
                "voiceId": "OAv0NDI9LZTkwNjsbe95",
                "modelId": "eleven_multilingual_v2"
              }
            }
          }
        },
        "memory": {
          "token": "[REDACTED]",
          "groupPolicy": "allowlist",
          "streaming": "off",
          "guilds": {
            "1476702984954970313": {
              "requireMention": false,
              "channels": {
                "1476702984954970316": {
                  "requireMention": false
                }
              }
            }
          },
          "threadBindings": {
            "enabled": true,
            "spawnSubagentSessions": true,
            "spawnAcpSessions": true
          },
          "voice": {
            "enabled": true,
            "tts": {
              "provider": "elevenlabs",
              "elevenlabs": {
                "voiceId": "HpSVTprBun63u96uF0up",
                "modelId": "eleven_multilingual_v2"
              }
            }
          }
        }
      }
    }
  },
  "gateway": {
    "mode": "local",
    "bind": "loopback",
    "customBindHost": "127.0.0.1",
    "auth": {
      "mode": "token",
      "token": "[REDACTED]"
    }
  },
  "skills": {
    "entries": {
      "sag": {
        "apiKey": "[REDACTED]"
      },
      "openai-whisper-api": {
        "apiKey": "[REDACTED]"
      },
      "openai-image-gen": {
        "apiKey": "[REDACTED]"
      }
    }
  },
  "plugins": {
    "entries": {
      "voice-call": {
        "enabled": true,
        "config": {
          "provider": "twilio",
          "fromNumber": "+19738603823",
          "twilio": {
            "accountSid": "$TWILIO_ACCOUNT_SID",
            "authToken": "$TWILIO_API_KEY_SECRET"
          },
          "serve": {
            "port": 3334,
            "path": "/voice/webhook"
          },
          "outbound": {
            "defaultMode": "conversation"
          },
          "streaming": {
            "enabled": true,
            "streamPath": "/voice/stream"
          },
          "tts": {
            "provider": "elevenlabs",
            "elevenlabs": {
              "apiKey": "[REDACTED]",
              "voiceId": "JBFqnCBsd6RMkjVDRZzb",
              "modelId": "eleven_multilingual_v2"
            }
          },
          "inboundPolicy": "allowlist",
          "allowFrom": [],
          "inboundGreeting": "Hey! This is Sean's assistant. What can I help you with?"
        }
      },
      "telegram": {
        "enabled": true,
        "config": {}
      },
      "acpx": {
        "enabled": true
      }
    }
  }
}

CONFIGEOF

chmod 600 "$CONFIG_FILE"
log "Config installed with 600 perms (CRITICAL fix #1) ✅"

###############################################################################
# Step 8: Agent Directories
###############################################################################
step "Step 8/9: Agent Directories"

# Create agent dirs for sisters that need them
mkdir -p "$OPENCLAW_DIR/agents/forge/agent"
mkdir -p "$OPENCLAW_DIR/agents/scholar/agent"

log "Agent directories created ✅"

###############################################################################
# Step 9: Start Gateway
###############################################################################
step "Step 9/9: Start Gateway"

log "Installing gateway service..."
openclaw gateway start 2>/dev/null || true

sleep 3
openclaw status 2>&1 | head -20

echo ""
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "  🔥 SAI Migration Complete!"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log ""
log "  Workspace:  $WORKSPACE"
log "  Config:     $CONFIG_FILE"
log "  Env:        $ENV_FILE"
log "  Sisters:    main, forge, scholar, memory, recovery"
log "  Postgres:   $DATABASE_URL"
log ""
log "  Next steps:"
log "    1. Verify: openclaw status --deep"
log "    2. Test Telegram: send me a message"
log "    3. Pair devices: openclaw pair"
log ""
log "  The Mac Studio is home now. 🔥"
